Use 2 cpus because writing the bamfiles to disk is a bottleneck Don't output duplicate reads Don't use `echo` in bash scripts Consistent variable naming in bash scripts

diff --git a/src/sh/bash_header b/src/sh/bash_header
--- a/src/sh/bash_header
+++ b/src/sh/bash_header
@@ -17,7 +17,7 @@ _err_trap() {
   local _cmd="${BASH_COMMAND:-unknown}"
   traceback 1
   _showed_traceback=t
-  echo "The command ${_cmd} exited with exit code ${_ec}." 1>&2
+  printf "The command %s exited with exit code %s.\n" "${_cmd}" "${_ec}" 1>&2
 }
 
 traceback() {
@@ -27,13 +27,13 @@ traceback() {
   local -i i=0
   local -i j=0
 
-  echo "Traceback (last called is first):" 1>&2
+  printf "Traceback (last called is first):\n" 1>&2
   for ((i=start; i < end; i++)); do
     j=$(( i - 1 ))
     local function="${FUNCNAME[$i]}"
     local file="${BASH_SOURCE[$i]}"
     local line="${BASH_LINENO[$j]}"
-    echo "     ${function}() in ${file}:${line}" 1>&2
+    printf "     %s() in %s:%s\n" "${function}" in "${file}" "${line}" 1>&2
   done
 }
 
@@ -43,23 +43,23 @@ trap _exit_trap EXIT
 trap _err_trap ERR
 
 # how many CPUs?
-if [[ $SLURM_JOB_CPUS_PER_NODE ]]; then
-  MAX_CPUS="$SLURM_JOB_CPUS_PER_NODE"
-  echo -e "[ $(date): Running with $MAX_CPUS CPUs ]"
+if [[ "${SLURM_JOB_CPUS_PER_NODE}" ]]; then
+  max_cpus="${SLURM_JOB_CPUS_PER_NODE}"
 else
-  MAX_CPUS=1
+  max_cpus=1
 fi
-let "RAM_LIMIT = $MAX_CPUS * 3000000000"
-echo -e "[ $(date): Allocating $((RAM_LIMIT/1000000000)) GB RAM ]"
+ram_limit=$((max_cpus*3000000000))
+printf "[ %s: Running with %s CPU(s) ]\n" "$(date)" "${max_cpus}"
+printf "[ %s: Allocating %s GB RAM ]\n" "$(date)" $((ram_limit/1000000000))
 
 # handle waiting
 FAIL=0
 fail_wait() {
 for job in $(jobs -p); do
-  wait "$job" || let "FAIL+=1"
+  wait "${job}" || let "FAIL+=1"
 done
-if [[ ! "$FAIL" == 0 ]]; then
-  echo -e "[ $(date): Detected fail in background job ]"
+if [[ ! "${FAIL}" == 0 ]]; then
+  printf "[ %s: Detected fail in background job ]\n" "$(date)"
   exit 1
 fi
 }
diff --git a/src/sh/mark_duplicates_and_sort b/src/sh/mark_duplicates_and_sort
--- a/src/sh/mark_duplicates_and_sort
+++ b/src/sh/mark_duplicates_and_sort
@@ -3,130 +3,131 @@
 # parse options
 OPTIND=1
 while getopts ":i:o:" opt; do
-    case "$opt" in
-        i)  input_files=$OPTARG
+    case "${opt}" in
+        i)  input_files="${OPTARG}"
             ;;
-        o)  output_files=$OPTARG
+        o)  output_files="${OPTARG}"
             ;;
         :)
-            echo "Option -$OPTARG requires an argument." >&2
+            printf "Option -%s requires an argument.\n" "${OPTARG}" >&2
             exit 1
             ;;
         \?)
-            echo "Invalid option: -$OPTARG" >&2
+            printf "Invalid option: -%s\n" "${OPTARG}" >&2
             exit 1
             ;;
     esac
 done
 shift "$((OPTIND-1))"
 
-printf " input_files: %s\n" "$input_files"
-printf "output_files: %s\n" "$output_files"
-
 source "src/sh/bash_header"
+
+printf " input_files: %s\n" "${input_files}"
+printf "output_files: %s\n" "${output_files}"
 
 ###############
 # CODE STARTS #
 ###############
 
-picard_ram=$((MAX_CPUS*3))"g"
-mrir=$((RAM_LIMIT/6000)) # max records in RAM
-ParallelGCThreads=$((MAX_CPUS-1)) # number of garbage collecting threads
+picard_ram=$((max_cpus*3))"g"
+mrir=$((ram_limit/6000)) # max records in RAM
+gc_threads=$((max_cpus-1)) # number of garbage collecting threads
 
-echo -e "[ $(date): Add read groups, sort, mark duplicates and create index ]"
+printf "[ %s: Add read groups, sort, deduplicate and create index ]\n" \
+       "$(date)"
 
 # make outdir
 outdir="output/mark_duplicates_and_sort"
-if [[ ! -d "$outdir" ]]; then
-    mkdir -p "$outdir"
+if [[ ! -d "${outdir}" ]]; then
+    mkdir -p "${outdir}"
 fi
 tmpdir="tmp"
-if [[ ! -d "$tmpdir" ]]; then
-    mkdir -p "$tmpdir"
+if [[ ! -d "${tmpdir}" ]]; then
+    mkdir -p "${tmpdir}"
 fi
 
 # parse RG information from BAM:
 # RGPU=flowcell+lane
-bam_line="$(samtools view "$input_files" | head -n 1)"
-flowcell="$(echo "$bam_line" | cut -d ':' -f 3)"
-lane="$(echo "$bam_line" | cut -d ':' -f 4)"
-rgpu="$flowcell"."$lane"
+bam_line="$(samtools view "${input_files}" | head -n 1)"
+flowcell="$(printf "%s" "${bam_line}" | cut -d ':' -f 3)"
+lane="$(printf "%s" "${bam_line}" | cut -d ':' -f 4)"
+rgpu="${flowcell}"."${lane}"
 # RGLB = library, RGID = library
-rglb="$(basename "$input_files" .Aligned.out.bam)"
+rglb="$(basename "${input_files}" .Aligned.out.bam)"
 # RGSM = sample
-rgid=${rglb:0:1}
-library_number=${rglb:1:1}
-if [[ "$library_number" -le 3 ]]; then
-    rgsm="$rgid.PBM"
+rgid="${rglb:0:1}"
+library_number="${rglb:1:1}"
+if [[ "${library_number}" -le 3 ]]; then
+    rgsm="${rgid}.PBM"
 else
-    rgsm="$rgid.SM"
+    rgsm="${rgid}.SM"
 fi
 
-echo -e "[ $(date): Setting read groups ]"
-printf "RGLB: %s\n" "$rglb"
-printf "RGSM: %s\n" "$rgsm"
-printf "RGPU: %s\n" "$rgpu"
+printf "[ %s: Setting read groups ]\n" "$(date)"
+printf "RGLB: %s\n" "${rglb}"
+printf "RGSM: %s\n" "${rgsm}"
+printf "RGPU: %s\n" "${rgpu}"
 
 # set output file
-sorted_bam_file="$outdir"/"$rglb".rg_added_sorted.bam
-log_file="$outdir"/"$rglb".AddOrReplaceReadGroups.log
+sorted_bam_file="${outdir}"/"${rglb}".rg_added_sorted.bam
+log_file="${outdir}"/"${rglb}".AddOrReplaceReadGroups.log
 
 # run AddOrReplaceReadGroups
-
-echo -e "[ $(date): Adding read groups and sorting BAM to file ]"
-printf "sorted_bam_file: %s\n" "$sorted_bam_file"
-printf "       log_file: %s\n" "$log_file"
-
-cmd1="java -Xmx$picard_ram -XX:ParallelGCThreads=$ParallelGCThreads \
+cmd1="java -Xmx${picard_ram} -XX:ParallelGCThreads=${gc_threads} \
         -jar bin/picard.jar \
         AddOrReplaceReadGroups \
-        MAX_RECORDS_IN_RAM=$mrir TMP_DIR=$tmpdir COMPRESSION_LEVEL=9 \
-        I=$input_files O=$sorted_bam_file \
-        SO=coordinate RGID=$rglb RGLB=$rglb RGSM=$rgsm RGPL=illumina \
-        RGPU=$rgpu"
+        MAX_RECORDS_IN_RAM=${mrir} TMP_DIR=${tmpdir} COMPRESSION_LEVEL=9 \
+        I=${input_files} O=${sorted_bam_file} SO=coordinate \
+        RGID=${rglb} RGLB=${rglb} RGSM=${rgsm} RGPL=illumina RGPU=${rgpu}"
 
-srun --ntasks=1 --cpus-per-task="$MAX_CPUS" --exclusive --job-name="$rglb"\
-    --output="$log_file" $cmd1 &
+printf "[ %s: Adding read groups and sorting BAM to file ]\n" "$(date)"
+printf "   sorted_bam_file: %s\n" "${sorted_bam_file}"
+printf "          log_file: %s\n" "${log_file}"
+printf "Final command line: %s\n" "${cmd1//+( )/ }" # remove multiple spaces
 
-echo -e "[ $(date): Waiting for AddOrReplaceReadGroups to finish ]"
+srun --ntasks=1 --cpus-per-task="${max_cpus}" --exclusive \
+    --job-name="${rglb}" --output="${log_file}" ${cmd1} &
+
+printf "[ %s: Waiting for AddOrReplaceReadGroups to finish ]\n" "$(date)"
 FAIL=0
 fail_wait
 
 # set output files
-dedupped_bam_file="$output_files"
-metrics_file="$outdir"/"$rglb".metrics
-log_file="$outdir"/"$rglb".MarkDuplicates.log
+dedupped_bam_file="${output_files}"
+metrics_file="${outdir}"/"${rglb}".metrics
+log_file="${outdir}"/"${rglb}".MarkDuplicates.log
 
 # run MarkDuplicates
-echo -e "[ $(date): Marking duplicates ]"
-printf "dedupped_bam_file: %s\n" "$dedupped_bam_file"
-printf "     metrics_file: %s\n" "$metrics_file"
-printf "         log_file: %s\n" "$log_file"
-
-cmd2="java -Xmx$picard_ram -XX:ParallelGCThreads=$ParallelGCThreads \
+cmd2="java -Xmx${picard_ram} -XX:ParallelGCThreads=${gc_threads} \
         -jar bin/picard.jar \
         MarkDuplicates \
-        MAX_RECORDS_IN_RAM=$mrir TMP_DIR=$tmpdir COMPRESSION_LEVEL=9 \
-        VALIDATION_STRINGENCY=SILENT \
-        I=$sorted_bam_file O=$dedupped_bam_file \
-        CREATE_INDEX=true  METRICS_FILE=$metrics_file"
+        MAX_RECORDS_IN_RAM=${mrir} TMP_DIR=${tmpdir} COMPRESSION_LEVEL=9 \
+        VALIDATION_STRINGENCY=SILENT REMOVE_DUPLICATES=true \
+        I=${sorted_bam_file} O=${dedupped_bam_file} \
+        CREATE_INDEX=true  METRICS_FILE=${metrics_file}"
 
-srun --ntasks=1 --cpus-per-task="$MAX_CPUS" --exclusive --job-name="$rglb"\
-    --output="$log_file" $cmd2 &
+printf "[ %s: Marking duplicates ]\n" "$(date)"
+printf " dedupped_bam_file: %s\n" "${dedupped_bam_file}"
+printf "      metrics_file: %s\n" "${metrics_file}"
+printf "          log_file: %s\n" "${log_file}"
+printf "Final command line: %s\n" "${cmd2//+( )/ }" # remove multiple spaces
 
-echo -e "[ $(date): Waiting for MarkDuplicates to finish ]"
+srun --ntasks=1 --cpus-per-task="${max_cpus}" --exclusive \
+    --job-name="${rglb}" --output="${log_file}" ${cmd2} &
+
+printf "[ %s: Waiting for MarkDuplicates to finish ]\n" "$(date)"
 FAIL=0
 fail_wait
 
 # tidy up intermediate file (not enough space to store)
-echo -e "[ $(date): Removing intermediate file ]"
-rm "$sorted_bam_file"
+printf "[ %s: Removing intermediate file ]\n" "$(date)"
+rm "${sorted_bam_file}"
 
 # log metadata
-metadata_file="$outdir"/"$rglb".METADATA.csv
-echo -e "[ $(date): Logging metadata ]"
-printf "metadata_file: %s\n" "$metadata_file"
-cat <<- _EOF_ > $metadata_file
+metadata_file="${outdir}"/"${rglb}".METADATA.csv
+printf "[ %s: Logging metadata ]\n" "$(date)"
+printf "metadata_file: %s\n" "${metadata_file}"
+cat <<- _EOF_ > ${metadata_file}
   Script,${0}
   branch,$(git rev-parse --abbrev-ref HEAD)
   hash,$(git rev-parse HEAD)
@@ -134,8 +135,8 @@ cat <<- _EOF_ > $metadata_file
   samtools version,$(samtools --version | head -n 1)
   picard-tools version,$(java -jar bin/picard.jar MarkDuplicates \
                             --version 2>&1)
-  output,"$outdir"
+  output,${outdir}
 _EOF_
 
-echo -e "[ $(date): Done, exiting ]"
+printf "[ %s: Done, exiting ]\n" "$(date)"
 exit 0
